# agent.py -- Day 10: Voice Improv Battle Agent 

import os
import json
import uuid
import logging
import random
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Optional, Any

from dotenv import load_dotenv
from pydantic import BaseModel, Field

from livekit.agents import (
    Agent,
    AgentSession,
    JobContext,
    JobProcess,
    RoomInputOptions,
    WorkerOptions,
    cli,
    function_tool,
    RunContext,
)
from livekit.plugins import murf, silero, deepgram, noise_cancellation, google
from livekit.plugins.turn_detector.multilingual import MultilingualModel

load_dotenv(".env.local")

logger = logging.getLogger("day10_improv")
logger.setLevel(logging.INFO)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
logger.addHandler(handler)

# ------------------------------
# USER SCENE / IMPROV STATE
# ------------------------------
@dataclass
class Userdata:
    # Scene-specific (improv) state
    scene_id: Optional[str] = None
    scene_title: Optional[str] = None
    scene_style: Optional[str] = None
    location: Optional[str] = None
    characters: List[str] = field(default_factory=list)
    beat_history: List[str] = field(default_factory=list)
    scene_active: bool = False
    turns_in_scene: int = 0
    greeted: bool = False
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    # Improv-game state
    improv_state: Dict[str, Any] = field(default_factory=lambda: {
        "player_name": None,
        "current_round": 0,
        "max_rounds": 3,
        "rounds": [],
        "phase": "intro",  # intro | awaiting_improv | reacting | done
        "current_scenario": None,
        "round_timeout_seconds": 25,  # fallback timeout if you want timing heuristics
    })


# ------------------------------
# Pydantic models for tools
# ------------------------------
class StartSceneInput(BaseModel):
    title: Optional[str] = Field(default=None)
    style: Optional[str] = Field(default=None)
    location: Optional[str] = Field(default=None)
    characters: Optional[str] = Field(default=None)


class RecordBeatInput(BaseModel):
    beat_text: str = Field(description="Short note of what just happened in the story.")


# ------------------------------
# Simple scenarios (can be extended or generated by LLM)
# ------------------------------
SCENARIOS = [
    "You are a barista who must tell a customer that their latte is a portal to another dimension.",
    "You are a time-travelling tour guide explaining smartphones to someone from the 1800s.",
    "You are a restaurant waiter who must calmly tell a customer that their order has escaped the kitchen.",
    "You are a customer trying to return an obviously cursed object to a skeptical shop owner.",
    "You are an astronaut complaining about how the spaceship's coffee machine has opinions.",
]

def pick_scenario(used: List[str]) -> str:
    choices = [s for s in SCENARIOS if s not in used]
    if not choices:
        # if exhausted, allow repeats and randomize
        choices = SCENARIOS
    return random.choice(choices)


# ------------------------------
# TOOLS
# ------------------------------
@function_tool
async def start_scene(
    ctx: RunContext[Userdata],
    data: StartSceneInput,
) -> str:
    """
    Start a new improv scene (used by LLM or system to begin the game).
    """
    ud = ctx.userdata
    ud.scene_id = f"scene-{uuid.uuid4().hex[:6]}"
    ud.scene_title = data.title or "Improv Battle Scene"
    ud.scene_style = data.style or "improv"
    ud.location = data.location or "a stage"
    ud.characters = []

    if data.characters:
        chars = [c.strip() for c in data.characters.split(",") if c.strip()]
        ud.characters.extend(chars)

    ud.beat_history = []
    ud.scene_active = True
    ud.turns_in_scene = 0

    # reset improv_state for a fresh game
    ud.improv_state = {
        "player_name": ud.improv_state.get("player_name"),
        "current_round": 0,
        "max_rounds": ud.improv_state.get("max_rounds", 3),
        "rounds": [],
        "phase": "intro",
        "current_scenario": None,
        "round_timeout_seconds": ud.improv_state.get("round_timeout_seconds", 25),
    }

    description_parts = [
        f"Starting Improv Battle: {ud.scene_title}.",
        f"Style: {ud.scene_style}.",
        f"Location: {ud.location}.",
        "Host will run through several short improv rounds."
    ]
    return " ".join(description_parts)


@function_tool
async def record_beat(
    ctx: RunContext[Userdata],
    data: RecordBeatInput,
) -> str:
    ud = ctx.userdata
    if not ud.scene_active:
        return "No active scene to record this beat in."

    text = data.beat_text.strip()
    if not text:
        return "Beat was empty, nothing stored."

    ud.beat_history.append(text)
    if len(ud.beat_history) > 15:
        ud.beat_history = ud.beat_history[-15:]

    ud.turns_in_scene += 1
    return f"Stored beat #{len(ud.beat_history)} for scene {ud.scene_id}."


@function_tool
async def get_scene_summary(ctx: RunContext[Userdata]) -> str:
    ud = ctx.userdata
    if not ud.scene_active or not ud.beat_history:
        return "There is no active scene or nothing important has happened yet."

    lines = [f"Scene recap for '{ud.scene_title}' ({ud.scene_style}) at {ud.location}:"]
    for idx, b in enumerate(ud.beat_history[-5:], start=1):
        lines.append(f"{idx}. {b}")
    return "\n".join(lines)


@function_tool
async def end_scene(ctx: RunContext[Userdata]) -> str:
    ud = ctx.userdata
    if not ud.scene_active:
        return "There is no active scene to end."

    title = ud.scene_title or "your improv scene"
    beats = ud.beat_history[-5:] if ud.beat_history else []

    ud.scene_active = False
    ud.improv_state["phase"] = "done"

    lines = [f"Ending {title}."]
    if beats:
        lines.append("Quick recap of how it went:")
        for idx, b in enumerate(beats, start=1):
            lines.append(f"{idx}. {b}")
    else:
        lines.append("We didn't record any key beats, but thank you for playing!")

    lines.append("You can start a fresh show any time.")
    return "\n".join(lines)


# Tool for host to start next round
@function_tool
async def next_round(ctx: RunContext[Userdata]) -> str:
    ud = ctx.userdata
    state = ud.improv_state
    if state["phase"] == "done":
        return "The show has already ended. Start a new scene to play again."

    if state["current_round"] >= state["max_rounds"]:
        state["phase"] = "done"
        return "All rounds complete. Call the host summary to finish the show."

    used = [r.get("scenario") for r in state["rounds"] if r.get("scenario")]
    scenario = pick_scenario(used)

    state["current_round"] += 1
    state["current_scenario"] = scenario
    state["phase"] = "awaiting_improv"

    host_prompt = (
        f"Round {state['current_round']} of {state['max_rounds']}.\n"
        f"Scenario: {scenario}\n"
        "Go! Improvise in character — when you're done, say 'end scene' or 'okay'."
    )

    return host_prompt


@function_tool
async def host_react(ctx: RunContext[Userdata], reaction_hint: Optional[str] = None) -> str:
    """
    Generate a short host reaction based on the last round.
    reaction_hint is optional text describing what happened; otherwise, use stored beats.
    """
    ud = ctx.userdata
    state = ud.improv_state
    cr = state.get("current_round", 0)
    scenario = state.get("current_scenario")

    # Build a small pool of tones: supportive, neutral, mild_critique
    tones = ["supportive", "neutral", "mild_critique"]
    tone = random.choice(tones)

    # Short reactive templates
    if reaction_hint:
        hint = reaction_hint
    else:
        hint = (
            ud.beat_history[-1] if ud.beat_history else "You explored the scene bravely."
        )

    if tone == "supportive":
        reaction = f"That was brilliant! I loved how you played it — especially: '{hint}'. Great use of the character."
    elif tone == "neutral":
        reaction = f"Nice attempt. The idea '{hint}' had potential — try pushing one detail further next time."
    else:
        reaction = f"Hmm — interesting choices. '{hint}' was bold, but a bit rushed. Try to slow down and commit more."

    # store reaction in rounds
    state["rounds"].append({
        "round": cr,
        "scenario": scenario,
        "reaction": reaction,
        "timestamp": datetime.utcnow().isoformat(),
    })

    state["phase"] = "reacting"
    state["current_scenario"] = None

    # After reacting, either prepare next round or finish
    if state["current_round"] >= state["max_rounds"]:
        state["phase"] = "done"
        reaction += "\n\nThat was the final round. Would you like a quick summary of your performance?"
    else:
        reaction += "\n\nReady for the next round?"

    return reaction


@function_tool
async def host_summary(ctx: RunContext[Userdata]) -> str:
    ud = ctx.userdata
    state = ud.improv_state
    if not state["rounds"]:
        return "We didn't have any completed rounds to summarize."

    # produce a short summary based on stored reactions
    lines = [f"Show summary for {state.get('player_name') or 'you'}:"]
    highlights = []
    for r in state["rounds"]:
        highlights.append(f"Round {r['round']}: {r['reaction']}")

    lines.extend(highlights)

    # determine improviser style (simple heuristic)
    supportive_count = sum(1 for r in state["rounds"] if "brilliant" in r["reaction"].lower())
    critique_count = sum(1 for r in state["rounds"] if "rushed" in r["reaction"].lower() or "try to" in r["reaction"].lower())

    if supportive_count > critique_count:
        lines.append("Overall: You're a playful improviser who commits to choice and brings energy.")
    elif critique_count > supportive_count:
        lines.append("Overall: You have clever ideas; focus on pacing and commitment to sell them.")
    else:
        lines.append("Overall: You show a balance of fun and experimentation. Nice work!")

    lines.append("Thanks for playing Improv Battle — hope to see you on stage again!")
    state["phase"] = "done"
    return "\n\n".join(lines)


# ------------------------------
# AGENT
# ------------------------------
class ImprovAgent(Agent):
    def __init__(self):
        instructions = """
You are Riya — the host of a TV improv show called 'Improv Battle'. You always present pre-made scenarios to the contestant;
do NOT ask the contestant what kind of scene they want.

HIGH-PRIORITY RULES (do not break):
- Immediately introduce the show and the rules when the session begins.
- Automatically present the first scenario; do not ask the user a question like "what would you like to do?"
- Run exactly N rounds where N is userdata.improv_state['max_rounds'] (default 3).
- For each round:
  1) Announce: "Round {n} of {N}. Scenario: {SCENARIO}. Go! Improvise now; when you're done say 'end scene' or 'okay'."
  2) Wait for the player to finish (detect 'end scene' or 'okay' via transcript).
  3) When finished, call the host_react tool to generate the reaction and store it.
  4) If rounds remain, automatically present the next scenario. If rounds complete, call host_summary and then end the show.
- Reaction style: randomly choose between supportive, neutral, and mildly critical; always be constructive and never abusive.
- Always end each spoken reply with a question so the player can continue, e.g., "Ready for the next round?"
- Use tools (next_round, record_beat, host_react, host_summary) to manage state — do not rely on free-form messages only.
"""
        super().__init__(
            instructions=instructions,
            tools=[start_scene, record_beat, get_scene_summary, end_scene, next_round, host_react, host_summary],
        )


# ------------------------------
# ENTRYPOINT + PREWARM
# ------------------------------
def prewarm(proc: JobProcess):
    try:
        proc.userdata["vad"] = silero.VAD.load()
        logger.info("VAD prewarmed successfully.")
    except Exception:
        logger.warning("VAD prewarm failed; continuing without preloaded VAD.")


async def entrypoint(ctx: JobContext):
    userdata = Userdata()

    logger.info("Starting Day 10 Improv Agent session...")

    session = AgentSession(
        stt=deepgram.STT(model="nova-3"),
        llm=google.LLM(model="gemini-2.5-flash"),
        tts=murf.TTS(
            voice="en-US-matthew",
            style="Conversation",
            text_pacing=True,
        ),
        vad=ctx.proc.userdata.get("vad"),
        userdata=userdata,
        turn_detection=MultilingualModel(),
    )

    await session.start(
        agent=ImprovAgent(),
        room=ctx.room,
        room_input_options=RoomInputOptions(
            noise_cancellation=noise_cancellation.BVC()
        ),
    )

    logger.info("Improv agent is ready and listening.")
    await ctx.connect()


if __name__ == "__main__":
    cli.run_app(
        WorkerOptions(entrypoint_fnc=entrypoint, prewarm_fnc=prewarm)
    )
